=== Kaleakash/fullstacktrainingforzensar/Eclipse Java Programs/XMLApp/bin/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Employee" xmlns:tns="http://www.example.org/Employee" elementFormDefault="qualified">

<element name="Employees">
<complexType>
	<sequence>
		<element name="Emp" minOccurs="2" maxOccurs="4">
			<complexType>
				<all>
				<element name="FirstName" type="string"></element>
				<element name="LastName" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="age" type="int"></element>
				</all>
			</complexType>
		</element>
	</sequence>
</complexType>
</element>

</schema>

=== Kaleakash/fullstacktrainingforzensar/Eclipse Java Programs/XMLApp/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employees xmlns:tns="http://www.example.org/Employee" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee src/Employee.xsd ">
  <tns:Emp>
    <tns:FirstName>Ravi</tns:FirstName>
    <tns:LastName>Kumar</tns:LastName>
    <tns:age>21</tns:age>
  </tns:Emp>
  <tns:Emp>
    <tns:FirstName></tns:FirstName>
   
    <tns:age>0</tns:age>
  </tns:Emp>
</tns:Employees>
